spring:
  profiles: local 
  data:
    mongodb:
       host: 15.164.151.130
       port: 27017
       database: chatbot3
       username: chatbot
       password: cotqht123!
       authentication-database: admin
       
server:
  port: 7070
 
logging:
  level:
    root: info
    


    
